version: "3"
services:
  php:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: server-app-deposito
    restart: always
    ports:
      - 80:80
    volumes:
      - ./www:/var/www/html
    links: 
      - mariadb:mariadb

  mariadb:
    image: mariadb:10.4.14
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment: 
        MYSQL_ROOT_PASSWORD: H40m4ruK
    volumes: 
        - ./db:/var/lib/mysql
    ports: 
        - "3306:3306"
volumes:
  www: {}
  db: {}