 
version: "3"
services:
  php:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: srevr-app-deposito
    restart: always
    ports:
      - 80:80
    volumes:
      - ./www:/var/www/html
volumes:
  www: {}